name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 21 * * *' # Runs daily at 9:00 pm
  workflow_dispatch:
jobs:
  update-readme-with-hashnode-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          template: "[$title]($url?utm_source=github&utm_medium=social&utm_campaign=Blog%20Listing)$newline"
          feed_list: 'https://drupalodyssey.com/blog/rss.xml'
